[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  for = "/data/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"
