[build]
  command = "npm run build"
  publish = "dist"

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Allow JSON files to be fetched from /data/...
[[headers]]
  for = "/data/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"