[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "frontend/netlify/functions"

[dev]
  command = "vite"
  targetPort = 5173
  port = 8888
  functions = "frontend/netlify/functions"
  publish = "frontend"
